export const BOOTSTRAP_AUTH_START = 'BOOTSTRAP_AUTH_START'
export const BOOTSTRAP_AUTH_END = 'BOOTSTRAP_AUTH_END'

export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR'

export const LOGOUT = 'LOGOUT'

export const TOKEN_REFRESHING = 'TOKEN_REFRESHING'
export const TOKEN_REFRESHED = 'TOKEN_REFRESHED'

export const UPDATE_USER = 'UPDATE_USER'

export const PATCH_USER = 'PATCH_USER'
